# Generated by Django 3.0.5 on 2020-04-24 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('from_email', models.CharField(max_length=512)),
                ('to_email', models.CharField(max_length=1024)),
                ('subject', models.CharField(max_length=256)),
                ('plain_content', models.TextField(blank=True, default='')),
                ('html_content', models.TextField(blank=True, default='')),
                ('sent_date', models.DateTimeField(null=True)),
                ('client_id_owner', models.TextField()),
                ('last_error', models.TextField(blank=True, default='')),
                ('retries', models.IntegerField(default=0)),
                ('next_retry_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('from_email', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=256)),
                ('plain_content', models.TextField(blank=True, default='')),
                ('html_content', models.TextField(blank=True, default='')),
                ('max_retries', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('allowed_clients', models.ManyToManyField(blank=True, help_text='The clients that can send emails using this template.', related_name='allowed_clients', related_query_name='allowed_client', to='api.Client', verbose_name='allowed_clients')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MailTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
