# Generated by Django 3.0.5 on 2020-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='allowed_clients',
            field=models.ManyToManyField(blank=True, help_text='The clients that can send emails using this template.', related_name='allowed_clients', related_query_name='allowed_client', to='api.Client', verbose_name='Allowed Clients'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
    ]
