# Generated by Django 3.0.5 on 2020-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200424_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='identifier',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
