# Generated by Django 3.0.5 on 2020-05-12 21:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='payload',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
    ]
