# Generated by Django 3.0.5 on 2020-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mailtemplate_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='identifier',
            field=models.SlugField(unique=True),
        ),
    ]
