# Generated by Django 3.0.5 on 2020-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200512_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='identifier',
            field=models.SlugField(max_length=256),
        ),
    ]
