# Generated by Django 3.0.5 on 2020-05-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200512_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='identifier',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mailtemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='locale',
        ),
    ]
