# Generated by Django 3.0.5 on 2020-05-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200523_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
