# Generated by Django 3.0.5 on 2021-02-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mailtemplate_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='bcc_email',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mail',
            name='cc_email',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
