# Generated by Django 3.0.5 on 2022-01-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210212_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='from_email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='from_email',
            field=models.CharField(max_length=254),
        ),
    ]
