# Generated by Django 3.0.5 on 2023-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mail_lock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='mjml_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
