# Generated by Django 3.0.5 on 2024-03-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mailtemplate_mjml_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MailTemplate'),
        ),
    ]
